### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by tingchihc** [declare-lab/HyperRED#1]
hi,
I very appreciate you to share the source code.
Could you share the pretrained model? Also, could you tell me how to run this model to test one example? I want to check the result.

thanks,

**Comment by chiayewken** [comment]
Hi, the pretrained model and steps for prediction are shown here: https://github.com/declare-lab/HyperRED#model-prediction

For more detailed examples, you can check our [colab demo](https://colab.research.google.com/drive/1R3nDZ278vUlPrjfJPoTB7fFA1JFN8h5-?usp=sharing) or [jupyter notebook](https://github.com/declare-lab/HyperRED/blob/master/demo.ipynb)
